### PR TITLE
Adding test framework

### PR DESCRIPTION
**Pull request by ohyde**
- Added resolve src folder for easy importing
- Setup jest test framework with snapshots
- Code coverage out the box
- Example container test
- Jest config inside the package.json ( will move babel and other configs in that too...thoughts on this? Was going to put the babel config in here too...I just don't like having loads of .config files at the root directory )

### CODE REVIEW

**Comment by kahyde** [comment]
It seems like you already have babel in package.json...what am I missing?

**Comment by ohyde** [comment]
Yeah, I have the package reference but I'm considering putting the configuration for babel in the package.json too. 

As I've written it out I've come to think it's not a great idea (it'll just make the package.json loud and complicated) but I also want a better way of organizing the configuration files ( I'm sure it must be possible to put them in a folder ). Otherwise, we end up with .gitignore, .babelrc, webpack_config.js and a myriad of other configuration files at the root of the project. 

I'll have a look tomorrow or maybe later today at a way of putting them in all in a folder and still getting picked up by the corresponding tools.

**Comment by ohyde** [comment]
Nevermind, you're right, I was confused between projects. 

Need to decide if that solution (babel config in package.json) works :)

**Comment by lucasschejtman** [comment]
Where do you draw the line with config files? What makes a particular configuration worthy of being in package.json ?

I'm inclined to make it all or nothing

**Pull request merged**
